// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/AlekseyZapadovnikov/DelayedNotifier/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// GetType provides a mock function for the type MockSender
func (_mock *MockSender) GetType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSender_GetType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetType'
type MockSender_GetType_Call struct {
	*mock.Call
}

// GetType is a helper method to define mock.On call
func (_e *MockSender_Expecter) GetType() *MockSender_GetType_Call {
	return &MockSender_GetType_Call{Call: _e.mock.On("GetType")}
}

func (_c *MockSender_GetType_Call) Run(run func()) *MockSender_GetType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_GetType_Call) Return(s string) *MockSender_GetType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSender_GetType_Call) RunAndReturn(run func() string) *MockSender_GetType_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockSender
func (_mock *MockSender) SendMessage(record *models.Record) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Record) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - record *models.Record
func (_e *MockSender_Expecter) SendMessage(record interface{}) *MockSender_SendMessage_Call {
	return &MockSender_SendMessage_Call{Call: _e.mock.On("SendMessage", record)}
}

func (_c *MockSender_SendMessage_Call) Run(run func(record *models.Record)) *MockSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Record
		if args[0] != nil {
			arg0 = args[0].(*models.Record)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_SendMessage_Call) Return(err error) *MockSender_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_SendMessage_Call) RunAndReturn(run func(record *models.Record) error) *MockSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
