// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AlekseyZapadovnikov/DelayedNotifier/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryNotificationRepository creates a new instance of MockRepositoryNotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryNotificationRepository {
	mock := &MockRepositoryNotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryNotificationRepository is an autogenerated mock type for the NotificationRepository type
type MockRepositoryNotificationRepository struct {
	mock.Mock
}

type MockRepositoryNotificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryNotificationRepository) EXPECT() *MockRepositoryNotificationRepository_Expecter {
	return &MockRepositoryNotificationRepository_Expecter{mock: &_m.Mock}
}

// DeleteByID provides a mock function for the type MockRepositoryNotificationRepository
func (_mock *MockRepositoryNotificationRepository) DeleteByID(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryNotificationRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockRepositoryNotificationRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepositoryNotificationRepository_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockRepositoryNotificationRepository_DeleteByID_Call {
	return &MockRepositoryNotificationRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockRepositoryNotificationRepository_DeleteByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepositoryNotificationRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryNotificationRepository_DeleteByID_Call) Return(err error) *MockRepositoryNotificationRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryNotificationRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockRepositoryNotificationRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepositoryNotificationRepository
func (_mock *MockRepositoryNotificationRepository) GetByID(ctx context.Context, id int64) (*models.Record, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.Record, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.Record); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryNotificationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepositoryNotificationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepositoryNotificationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepositoryNotificationRepository_GetByID_Call {
	return &MockRepositoryNotificationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepositoryNotificationRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepositoryNotificationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryNotificationRepository_GetByID_Call) Return(record *models.Record, err error) *MockRepositoryNotificationRepository_GetByID_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockRepositoryNotificationRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*models.Record, error)) *MockRepositoryNotificationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepositoryNotificationRepository
func (_mock *MockRepositoryNotificationRepository) Save(ctx context.Context, rec *models.Record) (int64, error) {
	ret := _mock.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Record) (int64, error)); ok {
		return returnFunc(ctx, rec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Record) int64); ok {
		r0 = returnFunc(ctx, rec)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.Record) error); ok {
		r1 = returnFunc(ctx, rec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryNotificationRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepositoryNotificationRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - rec *models.Record
func (_e *MockRepositoryNotificationRepository_Expecter) Save(ctx interface{}, rec interface{}) *MockRepositoryNotificationRepository_Save_Call {
	return &MockRepositoryNotificationRepository_Save_Call{Call: _e.mock.On("Save", ctx, rec)}
}

func (_c *MockRepositoryNotificationRepository_Save_Call) Run(run func(ctx context.Context, rec *models.Record)) *MockRepositoryNotificationRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Record
		if args[1] != nil {
			arg1 = args[1].(*models.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryNotificationRepository_Save_Call) Return(n int64, err error) *MockRepositoryNotificationRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepositoryNotificationRepository_Save_Call) RunAndReturn(run func(ctx context.Context, rec *models.Record) (int64, error)) *MockRepositoryNotificationRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
