// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AlekseyZapadovnikov/DelayedNotifier/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfiger creates a new instance of MockConfiger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfiger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfiger {
	mock := &MockConfiger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfiger is an autogenerated mock type for the Configer type
type MockConfiger struct {
	mock.Mock
}

type MockConfiger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfiger) EXPECT() *MockConfiger_Expecter {
	return &MockConfiger_Expecter{mock: &_m.Mock}
}

// GetServerAddress provides a mock function for the type MockConfiger
func (_mock *MockConfiger) GetServerAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServerAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfiger_GetServerAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerAddress'
type MockConfiger_GetServerAddress_Call struct {
	*mock.Call
}

// GetServerAddress is a helper method to define mock.On call
func (_e *MockConfiger_Expecter) GetServerAddress() *MockConfiger_GetServerAddress_Call {
	return &MockConfiger_GetServerAddress_Call{Call: _e.mock.On("GetServerAddress")}
}

func (_c *MockConfiger_GetServerAddress_Call) Run(run func()) *MockConfiger_GetServerAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiger_GetServerAddress_Call) Return(s string) *MockConfiger_GetServerAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfiger_GetServerAddress_Call) RunAndReturn(run func() string) *MockConfiger_GetServerAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaticFilesPath provides a mock function for the type MockConfiger
func (_mock *MockConfiger) GetStaticFilesPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStaticFilesPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockConfiger_GetStaticFilesPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaticFilesPath'
type MockConfiger_GetStaticFilesPath_Call struct {
	*mock.Call
}

// GetStaticFilesPath is a helper method to define mock.On call
func (_e *MockConfiger_Expecter) GetStaticFilesPath() *MockConfiger_GetStaticFilesPath_Call {
	return &MockConfiger_GetStaticFilesPath_Call{Call: _e.mock.On("GetStaticFilesPath")}
}

func (_c *MockConfiger_GetStaticFilesPath_Call) Run(run func()) *MockConfiger_GetStaticFilesPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiger_GetStaticFilesPath_Call) Return(s string) *MockConfiger_GetStaticFilesPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockConfiger_GetStaticFilesPath_Call) RunAndReturn(run func() string) *MockConfiger_GetStaticFilesPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifydService creates a new instance of MockNotifydService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifydService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifydService {
	mock := &MockNotifydService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifydService is an autogenerated mock type for the NotifydService type
type MockNotifydService struct {
	mock.Mock
}

type MockNotifydService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifydService) EXPECT() *MockNotifydService_Expecter {
	return &MockNotifydService_Expecter{mock: &_m.Mock}
}

// CreateNotify provides a mock function for the type MockNotifydService
func (_mock *MockNotifydService) CreateNotify(ctx context.Context, record *models.Record) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Record) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifydService_CreateNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotify'
type MockNotifydService_CreateNotify_Call struct {
	*mock.Call
}

// CreateNotify is a helper method to define mock.On call
//   - ctx context.Context
//   - record *models.Record
func (_e *MockNotifydService_Expecter) CreateNotify(ctx interface{}, record interface{}) *MockNotifydService_CreateNotify_Call {
	return &MockNotifydService_CreateNotify_Call{Call: _e.mock.On("CreateNotify", ctx, record)}
}

func (_c *MockNotifydService_CreateNotify_Call) Run(run func(ctx context.Context, record *models.Record)) *MockNotifydService_CreateNotify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Record
		if args[1] != nil {
			arg1 = args[1].(*models.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifydService_CreateNotify_Call) Return(err error) *MockNotifydService_CreateNotify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifydService_CreateNotify_Call) RunAndReturn(run func(ctx context.Context, record *models.Record) error) *MockNotifydService_CreateNotify_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNotifyByID provides a mock function for the type MockNotifydService
func (_mock *MockNotifydService) DeleteNotifyByID(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNotifyByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifydService_DeleteNotifyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNotifyByID'
type MockNotifydService_DeleteNotifyByID_Call struct {
	*mock.Call
}

// DeleteNotifyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockNotifydService_Expecter) DeleteNotifyByID(ctx interface{}, id interface{}) *MockNotifydService_DeleteNotifyByID_Call {
	return &MockNotifydService_DeleteNotifyByID_Call{Call: _e.mock.On("DeleteNotifyByID", ctx, id)}
}

func (_c *MockNotifydService_DeleteNotifyByID_Call) Run(run func(ctx context.Context, id int64)) *MockNotifydService_DeleteNotifyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifydService_DeleteNotifyByID_Call) Return(err error) *MockNotifydService_DeleteNotifyByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifydService_DeleteNotifyByID_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockNotifydService_DeleteNotifyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotifyStatByID provides a mock function for the type MockNotifydService
func (_mock *MockNotifydService) GetNotifyStatByID(ctx context.Context, id int64) (models.RecordStatus, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotifyStatByID")
	}

	var r0 models.RecordStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.RecordStatus, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.RecordStatus); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.RecordStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifydService_GetNotifyStatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotifyStatByID'
type MockNotifydService_GetNotifyStatByID_Call struct {
	*mock.Call
}

// GetNotifyStatByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockNotifydService_Expecter) GetNotifyStatByID(ctx interface{}, id interface{}) *MockNotifydService_GetNotifyStatByID_Call {
	return &MockNotifydService_GetNotifyStatByID_Call{Call: _e.mock.On("GetNotifyStatByID", ctx, id)}
}

func (_c *MockNotifydService_GetNotifyStatByID_Call) Run(run func(ctx context.Context, id int64)) *MockNotifydService_GetNotifyStatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifydService_GetNotifyStatByID_Call) Return(recordStatus models.RecordStatus, err error) *MockNotifydService_GetNotifyStatByID_Call {
	_c.Call.Return(recordStatus, err)
	return _c
}

func (_c *MockNotifydService_GetNotifyStatByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (models.RecordStatus, error)) *MockNotifydService_GetNotifyStatByID_Call {
	_c.Call.Return(run)
	return _c
}
