// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/AlekseyZapadovnikov/DelayedNotifier/internal/models"
	"github.com/AlekseyZapadovnikov/DelayedNotifier/internal/service/rabbit"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationCache creates a new instance of MockNotificationCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationCache {
	mock := &MockNotificationCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationCache is an autogenerated mock type for the NotificationCache type
type MockNotificationCache struct {
	mock.Mock
}

type MockNotificationCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationCache) EXPECT() *MockNotificationCache_Expecter {
	return &MockNotificationCache_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockNotificationCache
func (_mock *MockNotificationCache) Add(ctx context.Context, rec *models.Record) error {
	ret := _mock.Called(ctx, rec)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Record) error); ok {
		r0 = returnFunc(ctx, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationCache_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockNotificationCache_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - rec *models.Record
func (_e *MockNotificationCache_Expecter) Add(ctx interface{}, rec interface{}) *MockNotificationCache_Add_Call {
	return &MockNotificationCache_Add_Call{Call: _e.mock.On("Add", ctx, rec)}
}

func (_c *MockNotificationCache_Add_Call) Run(run func(ctx context.Context, rec *models.Record)) *MockNotificationCache_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Record
		if args[1] != nil {
			arg1 = args[1].(*models.Record)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationCache_Add_Call) Return(err error) *MockNotificationCache_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationCache_Add_Call) RunAndReturn(run func(ctx context.Context, rec *models.Record) error) *MockNotificationCache_Add_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockNotificationCache
func (_mock *MockNotificationCache) DeleteByID(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationCache_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockNotificationCache_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockNotificationCache_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockNotificationCache_DeleteByID_Call {
	return &MockNotificationCache_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockNotificationCache_DeleteByID_Call) Run(run func(ctx context.Context, id int64)) *MockNotificationCache_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationCache_DeleteByID_Call) Return(err error) *MockNotificationCache_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationCache_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockNotificationCache_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockNotificationCache
func (_mock *MockNotificationCache) GetByID(ctx context.Context, id int64) (*models.Record, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*models.Record, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *models.Record); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationCache_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockNotificationCache_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockNotificationCache_Expecter) GetByID(ctx interface{}, id interface{}) *MockNotificationCache_GetByID_Call {
	return &MockNotificationCache_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockNotificationCache_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockNotificationCache_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationCache_GetByID_Call) Return(record *models.Record, err error) *MockNotificationCache_GetByID_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockNotificationCache_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*models.Record, error)) *MockNotificationCache_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleadQueue creates a new instance of MockDeleadQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleadQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleadQueue {
	mock := &MockDeleadQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleadQueue is an autogenerated mock type for the DeleadQueue type
type MockDeleadQueue struct {
	mock.Mock
}

type MockDeleadQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleadQueue) EXPECT() *MockDeleadQueue_Expecter {
	return &MockDeleadQueue_Expecter{mock: &_m.Mock}
}

// ConsumeDelayedMessages provides a mock function for the type MockDeleadQueue
func (_mock *MockDeleadQueue) ConsumeDelayedMessages(ctx context.Context) (<-chan *rabbit.MessageWrapper, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeDelayedMessages")
	}

	var r0 <-chan *rabbit.MessageWrapper
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan *rabbit.MessageWrapper, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan *rabbit.MessageWrapper); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *rabbit.MessageWrapper)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeleadQueue_ConsumeDelayedMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeDelayedMessages'
type MockDeleadQueue_ConsumeDelayedMessages_Call struct {
	*mock.Call
}

// ConsumeDelayedMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeleadQueue_Expecter) ConsumeDelayedMessages(ctx interface{}) *MockDeleadQueue_ConsumeDelayedMessages_Call {
	return &MockDeleadQueue_ConsumeDelayedMessages_Call{Call: _e.mock.On("ConsumeDelayedMessages", ctx)}
}

func (_c *MockDeleadQueue_ConsumeDelayedMessages_Call) Run(run func(ctx context.Context)) *MockDeleadQueue_ConsumeDelayedMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeleadQueue_ConsumeDelayedMessages_Call) Return(messageWrapperCh <-chan *rabbit.MessageWrapper, err error) *MockDeleadQueue_ConsumeDelayedMessages_Call {
	_c.Call.Return(messageWrapperCh, err)
	return _c
}

func (_c *MockDeleadQueue_ConsumeDelayedMessages_Call) RunAndReturn(run func(ctx context.Context) (<-chan *rabbit.MessageWrapper, error)) *MockDeleadQueue_ConsumeDelayedMessages_Call {
	_c.Call.Return(run)
	return _c
}
